### PR TITLE
add lag info and adjust the order of output column

### PR DESCRIPTION
**Pull request by jipengzhu**
change list

1.  add lag info for offset
2.  adjust the order of output column
3.  adjust the format of some code

test result
```
[root@mty-003 stormkafkamon]# python stormkafkamon/monitor.py --zserver mty-001 --zport 2182 --topology product --spoutroot /kafkaspout --friendly
+---------+-----------+-----------+----------+------------+------------+------------+-------------------+-------------+-----------+
|  Broker |   Topic   | Partition | Earliest |   Latest   |  Current   |    Lag     |       Spout       |    Delta    |   Depth   |
+---------+-----------+-----------+----------+------------+------------+------------+-------------------+-------------+-----------+
| mty-001 | product_1 |     2     |    0     |    9758    |    9757    |     1      | product_1_spout_2 |  1.0 bytes  |   9.5KB   |
| mty-001 | product_1 |     8     |    0     | 1549922142 |   552099   | 1549370043 |  product_1_spout  |    1.4GB    |   1.4GB   |
| mty-001 | product_1 |     8     |    0     | 1549926035 | 1014938290 | 534987745  | product_1_spout_2 |   510.2MB   |   1.4GB   |
| mty-001 | product_1 |     11    |  571907  |  1573654   |   726298   |   847356   |  product_1_spout  |   827.5KB   |  978.3KB  |
| mty-001 | product_1 |     11    |  571907  |  1573654   |  1573626   |     28     | product_1_spout_2 |  28.0 bytes |  978.3KB  |
| mty-001 | product_1 |     17    | 2744610  |  8404961   |  4960706   |  3444255   |  product_1_spout  |    3.3MB    |   5.4MB   |
| mty-001 | product_1 |     17    | 2744610  |  8404967   |  8404945   |     22     | product_1_spout_2 |  22.0 bytes |   5.4MB   |
| mty-001 | product_1 |     20    |    0     |  1295422   |   882698   |   412724   |  product_1_spout  |   403.1KB   |   1.2MB   |
| mty-001 | product_1 |     20    |    0     |  1295422   |  1295413   |     9      | product_1_spout_2 |  9.0 bytes  |   1.2MB   |
| mty-001 | product_1 |     23    |    0     |    3904    |    3653    |    251     |  product_1_spout  | 251.0 bytes |   3.8KB   |
| mty-001 | product_1 |     23    |    0     |    3904    |    3904    |     0      | product_1_spout_2 |  0.0 bytes  |   3.8KB   |
| mty-002 | product_1 |     0     |    0     |    2843    |    2843    |     0      | product_1_spout_2 |  0.0 bytes  |   2.8KB   |
| mty-002 | product_1 |     3     |    0     |   668137   |   381466   |   286671   |  product_1_spout  |   280.0KB   |  652.5KB  |
| mty-002 | product_1 |     3     |    0     |   668137   |   668136   |     1      | product_1_spout_2 |  1.0 bytes  |  652.5KB  |
| mty-002 | product_1 |     9     |    0     |   737698   |   511510   |   226188   |  product_1_spout  |   220.9KB   |  720.4KB  |
| mty-002 | product_1 |     9     |    0     |   737698   |   737698   |     0      | product_1_spout_2 |  0.0 bytes  |  720.4KB  |
| mty-002 | product_1 |     12    |   362    |    362     |    362     |     0      |  product_1_spout  |  0.0 bytes  | 0.0 bytes |
| mty-002 | product_1 |     18    | 4027388  |  13235663  |  7577209   |  5658454   |  product_1_spout  |    5.4MB    |   8.8MB   |
| mty-002 | product_1 |     18    | 4027388  |  13235663  |  13235292  |    371     | product_1_spout_2 | 371.0 bytes |   8.8MB   |
| mty-002 | product_1 |     21    |    0     |   412297   |    108     |   412189   |  product_1_spout  |   402.5KB   |  402.6KB  |
| mty-002 | product_1 |     21    |    0     |   412297   |   412273   |     24     | product_1_spout_2 |  24.0 bytes |  402.6KB  |
| mty-003 | product_1 |     1     |  11815   |   23111    |   11815    |   11296    |  product_1_spout  |    11.0KB   |   11.0KB  |
| mty-003 | product_1 |     4     |    0     |   393237   |   243579   |   149658   |  product_1_spout  |   146.2KB   |  384.0KB  |
| mty-003 | product_1 |     4     |    0     |   393237   |   393237   |     0      | product_1_spout_2 |  0.0 bytes  |  384.0KB  |
| mty-003 | product_1 |     7     |    0     |  10130608  |   816228   |  9314380   |  product_1_spout  |    8.9MB    |   9.7MB   |
| mty-003 | product_1 |     7     |    0     |  10130608  |  10130495  |    113     | product_1_spout_2 | 113.0 bytes |   9.7MB   |
| mty-003 | product_1 |     10    |   384    |    384     |    384     |     0      |  product_1_spout  |  0.0 bytes  | 0.0 bytes |
| mty-003 | product_1 |     16    |    0     |   415116   |   239406   |   175710   |  product_1_spout  |   171.6KB   |  405.4KB  |
| mty-003 | product_1 |     16    |    0     |   415116   |   415105   |     11     | product_1_spout_2 |  11.0 bytes |  405.4KB  |
| mty-003 | product_1 |     19    | 2151011  |  4959175   |  3247674   |  1711501   |  product_1_spout  |    1.6MB    |   2.7MB   |
| mty-003 | product_1 |     19    | 2151011  |  4959178   |  4959167   |     11     | product_1_spout_2 |  11.0 bytes |   2.7MB   |
| mty-003 | product_1 |     22    |  149400  |   786528   |   149400   |   637128   |  product_1_spout  |   622.2KB   |  622.2KB  |
| mty-003 | product_1 |     22    |  149400  |   786528   |   786523   |     5      | product_1_spout_2 |  5.0 bytes  |  622.2KB  |
+---------+-----------+-----------+----------+------------+------------+------------+-------------------+-------------+-----------+

Number of brokers:       3
Number of partitions:    33
Total lag:               2107646145
Total delta:             2.0GB
Total broker depth:      2.9GB
```

### CODE REVIEW

**Comment by otoolep** [comment]
@jipengzhu lag is the same as delta. Why do you need to show it?

**Comment by jipengzhu** [comment]
@otoolep because lag is more intuitive and the message is processed by line not the size
so i want to known how many lines delayed

**Comment by otoolep** [comment]
OK.

Some  people may be relying on the order of these columns, so if you want this merged, you'll need to allow it to be controlled by command-line options, so the current behavior remains the default.

I suggest 1 option that allows the user to show lag instead of delta. E.g. `--show-lag`.  And another that does something like `--columns` which would take a comma-delimited list of column order.

**Comment by jipengzhu** [comment]
is this ok? 

I think  `--columns`  option is a little complex to use

-  keep old style without `--showlag` option

```
[root@mty-003 stormkafkamon]# python stormkafkamon/monitor.py --zserver mty-001 --zport 2182 --topology product --spoutroot /kafkaspout --friendly
+---------+-----------+-----------+----------+------------+-----------+-------------------+------------+-------------+
|  Broker |   Topic   | Partition | Earliest |   Latest   |   Depth   |       Spout       |  Current   |    Delta    |
+---------+-----------+-----------+----------+------------+-----------+-------------------+------------+-------------+
| mty-001 | product_1 |     2     |    0     |   10083    |   9.8KB   | product_1_spout_2 |   10083    |  0.0 bytes  |
| mty-001 | product_1 |     8     |    0     | 1626815955 |   1.5GB   |  product_1_spout  |   552099   |    1.5GB    |
| mty-001 | product_1 |     8     |    0     | 1626819941 |   1.5GB   | product_1_spout_2 | 1422253112 |   195.1MB   |
| mty-001 | product_1 |     11    |  571907  |  1589902   |  994.1KB  |  product_1_spout  |   726298   |   843.4KB   |
| mty-001 | product_1 |     11    |  571907  |  1589902   |  994.1KB  | product_1_spout_2 |  1589901   |  1.0 bytes  |
| mty-001 | product_1 |     17    | 2744610  |  8541221   |   5.5MB   |  product_1_spout  |  4960706   |    3.4MB    |
| mty-001 | product_1 |     17    | 2744610  |  8541227   |   5.5MB   | product_1_spout_2 |  8541196   |  31.0 bytes |
| mty-001 | product_1 |     20    |    0     |  1303279   |   1.2MB   |  product_1_spout  |   882698   |   410.7KB   |
| mty-001 | product_1 |     20    |    0     |  1303279   |   1.2MB   | product_1_spout_2 |  1303278   |  1.0 bytes  |
| mty-001 | product_1 |     23    |    0     |    3904    |   3.8KB   |  product_1_spout  |    3653    | 251.0 bytes |
| mty-001 | product_1 |     23    |    0     |    3904    |   3.8KB   | product_1_spout_2 |    3904    |  0.0 bytes  |
| mty-002 | product_1 |     0     |    0     |    2843    |   2.8KB   | product_1_spout_2 |    2843    |  0.0 bytes  |
| mty-002 | product_1 |     3     |    0     |   675916   |  660.1KB  |  product_1_spout  |   381466   |   287.5KB   |
| mty-002 | product_1 |     3     |    0     |   675916   |  660.1KB  | product_1_spout_2 |   675915   |  1.0 bytes  |
| mty-002 | product_1 |     9     |    0     |   737698   |  720.4KB  |  product_1_spout  |   511510   |   220.9KB   |
| mty-002 | product_1 |     9     |    0     |   737698   |  720.4KB  | product_1_spout_2 |   737698   |  0.0 bytes  |
| mty-002 | product_1 |     12    |   362    |    362     | 0.0 bytes |  product_1_spout  |    362     |  0.0 bytes  |
| mty-002 | product_1 |     18    | 4027388  |  13411643  |   8.9MB   |  product_1_spout  |  7577209   |    5.6MB    |
| mty-002 | product_1 |     18    | 4027388  |  13411643  |   8.9MB   | product_1_spout_2 |  13411642  |  1.0 bytes  |
| mty-002 | product_1 |     21    |    0     |   420020   |  410.2KB  |  product_1_spout  |    108     |   410.1KB   |
| mty-002 | product_1 |     21    |    0     |   420020   |  410.2KB  | product_1_spout_2 |   420000   |  20.0 bytes |
| mty-003 | product_1 |     1     |  11815   |   23111    |   11.0KB  |  product_1_spout  |   11815    |    11.0KB   |
| mty-003 | product_1 |     4     |    0     |   393237   |  384.0KB  |  product_1_spout  |   243579   |   146.2KB   |
| mty-003 | product_1 |     4     |    0     |   393237   |  384.0KB  | product_1_spout_2 |   393237   |  0.0 bytes  |
| mty-003 | product_1 |     7     |    0     |  10422459  |   9.9MB   |  product_1_spout  |   816228   |    9.2MB    |
| mty-003 | product_1 |     7     |    0     |  10422459  |   9.9MB   | product_1_spout_2 |  10422458  |  1.0 bytes  |
| mty-003 | product_1 |     10    |   384    |    384     | 0.0 bytes |  product_1_spout  |    384     |  0.0 bytes  |
| mty-003 | product_1 |     16    |    0     |   425651   |  415.7KB  |  product_1_spout  |   239406   |   181.9KB   |
| mty-003 | product_1 |     16    |    0     |   425651   |  415.7KB  | product_1_spout_2 |   425641   |  10.0 bytes |
| mty-003 | product_1 |     19    | 2151011  |  5017825   |   2.7MB   |  product_1_spout  |  3247674   |    1.7MB    |
| mty-003 | product_1 |     19    | 2151011  |  5017828   |   2.7MB   | product_1_spout_2 |  5017820   |  8.0 bytes  |
| mty-003 | product_1 |     22    |  149400  |   788731   |  624.3KB  |  product_1_spout  |   149400   |   624.3KB   |
| mty-003 | product_1 |     22    |  149400  |   788731   |  624.3KB  | product_1_spout_2 |   788730   |  1.0 bytes  |
+---------+-----------+-----------+----------+------------+-----------+-------------------+------------+-------------+

Number of brokers:       3
Number of partitions:    33
Total broker depth:      3.1GB
Total delta:             1.7GB
```

- use new style with `--showlag` option

```
[root@mty-003 stormkafkamon]# python stormkafkamon/monitor.py --zserver mty-001 --zport 2182 --topology product --spoutroot /kafkaspout --friendly --showlag
+---------+-----------+-----------+----------+------------+------------+------------+-------------------+-------------+-----------+
|  Broker |   Topic   | Partition | Earliest |   Latest   |  Current   |    Lag     |       Spout       |    Delta    |   Depth   |
+---------+-----------+-----------+----------+------------+------------+------------+-------------------+-------------+-----------+
| mty-001 | product_1 |     2     |    0     |   10083    |   10083    |     0      | product_1_spout_2 |  0.0 bytes  |   9.8KB   |
| mty-001 | product_1 |     8     |    0     | 1627560249 |   552099   | 1627008150 |  product_1_spout  |    1.5GB    |   1.5GB   |
| mty-001 | product_1 |     8     |    0     | 1627564230 | 1429700933 | 197863297  | product_1_spout_2 |   188.7MB   |   1.5GB   |
| mty-001 | product_1 |     11    |  571907  |  1589947   |   726298   |   863649   |  product_1_spout  |   843.4KB   |  994.2KB  |
| mty-001 | product_1 |     11    |  571907  |  1589947   |  1589940   |     7      | product_1_spout_2 |  7.0 bytes  |  994.2KB  |
| mty-001 | product_1 |     17    | 2744610  |  8542531   |  4960706   |  3581825   |  product_1_spout  |    3.4MB    |   5.5MB   |
| mty-001 | product_1 |     17    | 2744610  |  8542537   |  8542489   |     48     | product_1_spout_2 |  48.0 bytes |   5.5MB   |
| mty-001 | product_1 |     20    |    0     |  1303355   |   882698   |   420657   |  product_1_spout  |   410.8KB   |   1.2MB   |
| mty-001 | product_1 |     20    |    0     |  1303355   |  1303354   |     1      | product_1_spout_2 |  1.0 bytes  |   1.2MB   |
| mty-001 | product_1 |     23    |    0     |    3904    |    3653    |    251     |  product_1_spout  | 251.0 bytes |   3.8KB   |
| mty-001 | product_1 |     23    |    0     |    3904    |    3904    |     0      | product_1_spout_2 |  0.0 bytes  |   3.8KB   |
| mty-002 | product_1 |     0     |    0     |    2843    |    2843    |     0      | product_1_spout_2 |  0.0 bytes  |   2.8KB   |
| mty-002 | product_1 |     3     |    0     |   675996   |   381466   |   294530   |  product_1_spout  |   287.6KB   |  660.2KB  |
| mty-002 | product_1 |     3     |    0     |   675996   |   675995   |     1      | product_1_spout_2 |  1.0 bytes  |  660.2KB  |
| mty-002 | product_1 |     9     |    0     |   737698   |   511510   |   226188   |  product_1_spout  |   220.9KB   |  720.4KB  |
| mty-002 | product_1 |     9     |    0     |   737698   |   737698   |     0      | product_1_spout_2 |  0.0 bytes  |  720.4KB  |
| mty-002 | product_1 |     12    |   362    |    362     |    362     |     0      |  product_1_spout  |  0.0 bytes  | 0.0 bytes |
| mty-002 | product_1 |     18    | 4027388  |  13413266  |  7577209   |  5836057   |  product_1_spout  |    5.6MB    |   9.0MB   |
| mty-002 | product_1 |     18    | 4027388  |  13413266  |  13413265  |     1      | product_1_spout_2 |  1.0 bytes  |   9.0MB   |
| mty-002 | product_1 |     21    |    0     |   420108   |    108     |   420000   |  product_1_spout  |   410.2KB   |  410.3KB  |
| mty-002 | product_1 |     21    |    0     |   420108   |   420082   |     26     | product_1_spout_2 |  26.0 bytes |  410.3KB  |
| mty-003 | product_1 |     1     |  11815   |   23111    |   11815    |   11296    |  product_1_spout  |    11.0KB   |   11.0KB  |
| mty-003 | product_1 |     4     |    0     |   393237   |   243579   |   149658   |  product_1_spout  |   146.2KB   |  384.0KB  |
| mty-003 | product_1 |     4     |    0     |   393237   |   393237   |     0      | product_1_spout_2 |  0.0 bytes  |  384.0KB  |
| mty-003 | product_1 |     7     |    0     |  10424643  |   816228   |  9608415   |  product_1_spout  |    9.2MB    |   9.9MB   |
| mty-003 | product_1 |     7     |    0     |  10424643  |  10424642  |     1      | product_1_spout_2 |  1.0 bytes  |   9.9MB   |
| mty-003 | product_1 |     10    |   384    |    384     |    384     |     0      |  product_1_spout  |  0.0 bytes  | 0.0 bytes |
| mty-003 | product_1 |     16    |    0     |   425739   |   239406   |   186333   |  product_1_spout  |   182.0KB   |  415.8KB  |
| mty-003 | product_1 |     16    |    0     |   425739   |   425738   |     1      | product_1_spout_2 |  1.0 bytes  |  415.8KB  |
| mty-003 | product_1 |     19    | 2151011  |  5018395   |  3247674   |  1770721   |  product_1_spout  |    1.7MB    |   2.7MB   |
| mty-003 | product_1 |     19    | 2151011  |  5018398   |  5018387   |     11     | product_1_spout_2 |  11.0 bytes |   2.7MB   |
| mty-003 | product_1 |     22    |  149400  |   788734   |   149400   |   639334   |  product_1_spout  |   624.3KB   |  624.3KB  |
| mty-003 | product_1 |     22    |  149400  |   788734   |   788733   |     1      | product_1_spout_2 |  1.0 bytes  |  624.3KB  |
+---------+-----------+-----------+----------+------------+------------+------------+-------------------+-------------+-----------+

Number of brokers:       3
Number of partitions:    33
Total lag:               1848880459
Total delta:             1.7GB
Total broker depth:      3.1GB
```

**Comment by otoolep** [comment]
Works for me -- thanks.

**Pull request merged**
