### PR TITLE
DRY up show lag handling

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
@jipengzhu -- I'd like to DRY up the code a little. Look good to you?

**Comment by jipengzhu** [comment]
@otoolep The independent method makes the logic more clearer , will it be better?

**Comment by otoolep** [comment]
@jipengzhu -- I know what you're saying, but I feel there is too much repeated code with the previous way.

**Comment by jipengzhu** [comment]
ok  👌

**Comment by otoolep** [comment]
Thanks @jipengzhu

**Comment by otoolep** [comment]
@jipengzhu -- I will say that the code here is pretty basic, it was written quite a while ago. It could do with a serious refactor, if you felt like it. I'm sure you could make it nicer and still retain the current default behavior.

**Comment by jipengzhu** [comment]
@otoolep 

ok, thanks.
if i have enough time ,  i will do it.

**Pull request merged**
